name: Govulncheck Security Scan

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/dependabot.yml"

jobs:
  govulncheck-check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
        cache: false
    - name: Install Govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: Run govulncheck
      run: govulncheck ./...

