name: Run tests

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/dependabot.yml"

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - oldstable
          - stable
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run go vet
        run: go vet ./...
      - name: Run Tests
        run: go test -v ./...
      - name: Run Tests (race)
        run: go test -v -race ./...
